#缩进时不允许使用Tab键，只能使用空格，空格的数目不重要，只要相同层级的元素左侧对齐即可
spring:
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: root
  servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB
        enabled: true
server:
  port: 80
logging:
  level:
    org:
      springframework: error
    com:
      myhopu:
        mapper: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml